name: Publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build-and-push-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and publish
        uses: oc-ulos/upt-packager@release
